version: '2'

services:

  certs:
    # build: https://github.com/robinzimmermann/docker.tutorials.git#certs:tls/cert-generator
    # image: ca-generator:server
    # docker build -t cert-generator .
    # docker run --name cert-generator --rm -v $PWD/x509:/x509 cert-generator server
    # To get the files: docker cp 2tls_certs_1:/x509 .
    build: cert-generator
    volumes:
      - x509:/x509

  example.com:
    image: kaazing/enterprise-gateway:5.7.0
    volumes:
      - ./config/cloud-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
      - ./utils/wait-for-files.sh:/wait-for-files.sh:ro
      - x509:/x509:ro
    ports:
      - "5551:5551"
      - "7771:7771"
    networks:
      kwic-net:
    command: bash -c "/wait-for-files.sh
                         /x509/stores/keystore-cloud.jceks
                         /x509/stores/keystore-cloud.pw
                         /x509/stores/truststore-cloud.jceks
                         /x509/stores/truststore-cloud.pw
                      && sleep 1
                      && gateway.start"


  tenant101:
    image: kaazing/enterprise-gateway:5.7.0
    volumes:
      - ./config/tenant101-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
      - ./utils/wait-for-files.sh:/wait-for-files.sh:ro
      - x509:/x509:ro
    ports:
      - "6661:6661"
    networks:
      kwic-net:
        ipv4_address: 172.33.0.101
    command: bash -c "/wait-for-files.sh
                         /x509/stores/keystore-tenant101.jceks
                         /x509/stores/keystore-tenant101.pw
                         /x509/stores/truststore-tenant101.jceks
                         /x509/stores/truststore-tenant101.pw
                      && sleep 1
                      && gateway.start"

  tenant201:
    image: kaazing/enterprise-gateway:5.7.0
    volumes:
      - ./config/tenant201-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
      - ./utils/wait-for-files.sh:/wait-for-files.sh:ro
      - x509:/x509:ro
    ports:
      - "9991:6661"
    networks:
      kwic-net:
        ipv4_address: 172.33.0.201
    command: bash -c "/wait-for-files.sh
                         /x509/stores/keystore-tenant201.jceks
                         /x509/stores/keystore-tenant201.pw
                         /x509/stores/truststore-tenant201.jceks
                         /x509/stores/truststore-tenant201.pw
                      && sleep 1
                      && gateway.start"

  server-a:
    image: kaazing/enterprise-gateway:5.7.0
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-a -Dservice-port=5551"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

  server-b:
    image: kaazing/enterprise-gateway:5.7.0
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-b -Dservice-port=6661"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

  server-c:
    image: kaazing/enterprise-gateway:5.7.0
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-c -Dservice-port=7771"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

volumes:
  x509:

networks:
  kwic-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.1
