# There is no official image of activemq yet so we will use the one that ships with the gateway
FROM kaazing/enterprise-gateway:latest

CMD ["java","-jar","brokers/apache-activemq-5.10.0/bin/activemq.jar","start"]

